version: '3.8'

services:
  db:
    image: postgres:14.11
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: